export const PassedData = [
  {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  },
  {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  }, {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  }, {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  },
  {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  },
  {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  }, {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  }, {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  },
  {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  },
  {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  }, {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed", 
    period: "a month ago",
  }, {
    id: 1,
    rank: "#200",
    eventNo: "2023",
    eventName: "Goud Events Resourcing Proposal",
    caption: "CommunitypoolSpendProposal",
    progress1: "57.76",
    progress2: 4,
    progress3: 5,
    progress4: 7,
    status: "passed",
    period: "a month ago",
  },
];
