export const RejectedData = [
  {
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },
  {
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },{
    id: 1,
    rank: "#200",
    eventName: "ATOM Airdrop",
    caption: "CommunitypoolSpendProposal",
    progress: 20,
    progress1: "57.76",
    status: "Rejected",
    period: "a month ago",
  },
];
